export const ADD_TOUR = 'ADD_TOUR';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FETCH_TOURS_REQUEST = 'FETCH_TOURS_REQUEST';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILURE = 'FETCH_TOURS_FAILURE';
