export const ADD_TOUR = 'ADD_TOUR';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FETCH_TOURS_REQUEST = 'FETCH_TOURS_REQUEST';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILURE = 'FETCH_TOURS_FAILURE';

export const ORDER_TOURS_BY_PRICE_DESC = 'ORDER_TOURS_BY_PRICE_DESC';
export const ORDER_TOURS_BY_PRICE_ASC = 'ORDER_TOURS_BY_PRICE_ASC';

export const ORDER_TOURS_BY_DESCRIPTION_DESC = 'ORDER_TOURS_BY_DESCRIPTION_DESC';
export const ORDER_TOURS_BY_DESCRIPTION_ASC = 'ORDER_TOURS_BY_DESCRIPTION_ASC';

/* for tokens */
export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';

/* for cities */
export const LIST_CITIES = 'LIST_CITIES';

/* for the input search */
export const FETCH_CITY = 'FETCH_CITY';

export const FETCH_TOKEN = 'FETCH_TOKEN';

/* alerts  */
export const SHOW_ALERT_ERROR = 'SHOW_ALERT_ERROR';
export const SHOW_ALERT_WARNING = 'SHOW_ALERT_WARNING';
export const HIDE_ALERT_WARNING = 'HIDE_ALERT_WARNING';
export const SHOW_ALERT_SUCCESS = 'SHOW_ALERT_SUCCESS';
