export function getStates(term = '') {
  if (term.length < 2) {
    return [];
  }
  return [
    {
      city: 'Tokyo',
      city_ascii: 'Tokyo',
      lat: 35.685,
      lng: 139.7514,
      country: 'Japan',
      iso2: 'JP',
      iso3: 'JPN',
      admin_name: 'Tōkyō',
      capital: 'primary',
      population: 35676000,
      id: 1392685764,
    },
    {
      city: 'New York',
      city_ascii: 'New York',
      lat: 40.6943,
      lng: -73.9249,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'New York',
      capital: '',
      population: 19354922,
      id: 1840034016,
    },
    {
      city: 'Mexico City',
      city_ascii: 'Mexico City',
      lat: 19.4424,
      lng: -99.131,
      country: 'Mexico',
      iso2: 'MX',
      iso3: 'MEX',
      admin_name: 'Ciudad de México',
      capital: 'primary',
      population: 19028000,
      id: 1484247881,
    },
    {
      city: 'Mumbai',
      city_ascii: 'Mumbai',
      lat: 19.017,
      lng: 72.857,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Mahārāshtra',
      capital: 'admin',
      population: 18978000,
      id: 1356226629,
    },
    {
      city: 'São Paulo',
      city_ascii: 'Sao Paulo',
      lat: -23.5587,
      lng: -46.625,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'São Paulo',
      capital: 'admin',
      population: 18845000,
      id: 1076532519,
    },
    {
      city: 'Delhi',
      city_ascii: 'Delhi',
      lat: 28.67,
      lng: 77.23,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Delhi',
      capital: 'admin',
      population: 15926000,
      id: 1356872604,
    },
    {
      city: 'Shanghai',
      city_ascii: 'Shanghai',
      lat: 31.2165,
      lng: 121.4365,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Shanghai',
      capital: 'admin',
      population: 14987000,
      id: 1156073548,
    },
    {
      city: 'Kolkata',
      city_ascii: 'Kolkata',
      lat: 22.495,
      lng: 88.3247,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'West Bengal',
      capital: 'admin',
      population: 14787000,
      id: 1356060520,
    },
    {
      city: 'Los Angeles',
      city_ascii: 'Los Angeles',
      lat: 34.1139,
      lng: -118.4068,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'California',
      capital: '',
      population: 12815475,
      id: 1840020491,
    },
    {
      city: 'Dhaka',
      city_ascii: 'Dhaka',
      lat: 23.7231,
      lng: 90.4086,
      country: 'Bangladesh',
      iso2: 'BD',
      iso3: 'BGD',
      admin_name: 'Dhaka',
      capital: 'primary',
      population: 12797394,
      id: 1050529279,
    },
    {
      city: 'Buenos Aires',
      city_ascii: 'Buenos Aires',
      lat: -34.6025,
      lng: -58.3975,
      country: 'Argentina',
      iso2: 'AR',
      iso3: 'ARG',
      admin_name: 'Buenos Aires, Ciudad Autónoma de',
      capital: 'primary',
      population: 12795000,
      id: 1032717330,
    },
    {
      city: 'Karachi',
      city_ascii: 'Karachi',
      lat: 24.87,
      lng: 66.99,
      country: 'Pakistan',
      iso2: 'PK',
      iso3: 'PAK',
      admin_name: 'Sindh',
      capital: 'admin',
      population: 12130000,
      id: 1586129469,
    },
    {
      city: 'Cairo',
      city_ascii: 'Cairo',
      lat: 30.05,
      lng: 31.25,
      country: 'Egypt',
      iso2: 'EG',
      iso3: 'EGY',
      admin_name: 'Al Qāhirah',
      capital: 'primary',
      population: 11893000,
      id: 1818253931,
    },
    {
      city: 'Rio de Janeiro',
      city_ascii: 'Rio de Janeiro',
      lat: -22.925,
      lng: -43.225,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Rio de Janeiro',
      capital: 'admin',
      population: 11748000,
      id: 1076887657,
    },
    {
      city: 'Ōsaka',
      city_ascii: 'Osaka',
      lat: 34.75,
      lng: 135.4601,
      country: 'Japan',
      iso2: 'JP',
      iso3: 'JPN',
      admin_name: 'Ōsaka',
      capital: 'admin',
      population: 11294000,
      id: 1392419823,
    },
    {
      city: 'Beijing',
      city_ascii: 'Beijing',
      lat: 39.9289,
      lng: 116.3883,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Beijing',
      capital: 'primary',
      population: 11106000,
      id: 1156228865,
    },
    {
      city: 'Manila',
      city_ascii: 'Manila',
      lat: 14.6042,
      lng: 120.9822,
      country: 'Philippines',
      iso2: 'PH',
      iso3: 'PHL',
      admin_name: 'Manila',
      capital: 'primary',
      population: 11100000,
      id: 1608618140,
    },
    {
      city: 'Moscow',
      city_ascii: 'Moscow',
      lat: 55.7522,
      lng: 37.6155,
      country: 'Russia',
      iso2: 'RU',
      iso3: 'RUS',
      admin_name: 'Moskva',
      capital: 'primary',
      population: 10452000,
      id: 1643318494,
    },
    {
      city: 'Istanbul',
      city_ascii: 'Istanbul',
      lat: 41.105,
      lng: 29.01,
      country: 'Turkey',
      iso2: 'TR',
      iso3: 'TUR',
      admin_name: 'İstanbul',
      capital: 'admin',
      population: 10061000,
      id: 1792756324,
    },
    {
      city: 'Paris',
      city_ascii: 'Paris',
      lat: 48.8667,
      lng: 2.3333,
      country: 'France',
      iso2: 'FR',
      iso3: 'FRA',
      admin_name: 'Île-de-France',
      capital: 'primary',
      population: 9904000,
      id: 1250015082,
    },
    {
      city: 'Seoul',
      city_ascii: 'Seoul',
      lat: 37.5663,
      lng: 126.9997,
      country: 'Korea, South',
      iso2: 'KR',
      iso3: 'KOR',
      admin_name: 'Seoul',
      capital: 'primary',
      population: 9796000,
      id: 1410836482,
    },
    {
      city: 'Lagos',
      city_ascii: 'Lagos',
      lat: 6.4433,
      lng: 3.3915,
      country: 'Nigeria',
      iso2: 'NG',
      iso3: 'NGA',
      admin_name: 'Lagos',
      capital: 'minor',
      population: 9466000,
      id: 1566593751,
    },
    {
      city: 'Jakarta',
      city_ascii: 'Jakarta',
      lat: -6.1744,
      lng: 106.8294,
      country: 'Indonesia',
      iso2: 'ID',
      iso3: 'IDN',
      admin_name: 'Jakarta',
      capital: 'primary',
      population: 9125000,
      id: 1360771077,
    },
    {
      city: 'Guangzhou',
      city_ascii: 'Guangzhou',
      lat: 23.145,
      lng: 113.325,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Guangdong',
      capital: 'admin',
      population: 8829000,
      id: 1156237133,
    },
    {
      city: 'Chicago',
      city_ascii: 'Chicago',
      lat: 41.8373,
      lng: -87.6862,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Illinois',
      capital: '',
      population: 8675982,
      id: 1840000494,
    },
    {
      city: 'London',
      city_ascii: 'London',
      lat: 51.5,
      lng: -0.1167,
      country: 'United Kingdom',
      iso2: 'GB',
      iso3: 'GBR',
      admin_name: 'London, City of',
      capital: 'primary',
      population: 8567000,
      id: 1826645935,
    },
    {
      city: 'Lima',
      city_ascii: 'Lima',
      lat: -12.048,
      lng: -77.0501,
      country: 'Peru',
      iso2: 'PE',
      iso3: 'PER',
      admin_name: 'Lima',
      capital: 'primary',
      population: 8012000,
      id: 1604728603,
    },
    {
      city: 'Tehran',
      city_ascii: 'Tehran',
      lat: 35.6719,
      lng: 51.4243,
      country: 'Iran',
      iso2: 'IR',
      iso3: 'IRN',
      admin_name: 'Tehrān',
      capital: 'primary',
      population: 7873000,
      id: 1364305026,
    },
    {
      city: 'Kinshasa',
      city_ascii: 'Kinshasa',
      lat: -4.3297,
      lng: 15.315,
      country: 'Congo (Kinshasa)',
      iso2: 'CD',
      iso3: 'COD',
      admin_name: 'Kinshasa',
      capital: 'primary',
      population: 7843000,
      id: 1180000363,
    },
    {
      city: 'Bogotá',
      city_ascii: 'Bogota',
      lat: 4.5964,
      lng: -74.0833,
      country: 'Colombia',
      iso2: 'CO',
      iso3: 'COL',
      admin_name: 'Bogotá',
      capital: 'primary',
      population: 7772000,
      id: 1170483426,
    },
    {
      city: 'Shenzhen',
      city_ascii: 'Shenzhen',
      lat: 22.5524,
      lng: 114.1221,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Guangdong',
      capital: 'minor',
      population: 7581000,
      id: 1156158707,
    },
    {
      city: 'Wuhan',
      city_ascii: 'Wuhan',
      lat: 30.58,
      lng: 114.27,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Hubei',
      capital: 'admin',
      population: 7243000,
      id: 1156117184,
    },
    {
      city: 'Hong Kong',
      city_ascii: 'Hong Kong',
      lat: 22.305,
      lng: 114.185,
      country: 'Hong Kong',
      iso2: 'HK',
      iso3: 'HKG',
      admin_name: '',
      capital: '',
      population: 7206000,
      id: 1344982653,
    },
    {
      city: 'Tianjin',
      city_ascii: 'Tianjin',
      lat: 39.13,
      lng: 117.2,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Tianjin',
      capital: 'admin',
      population: 7180000,
      id: 1156174046,
    },
    {
      city: 'Chennai',
      city_ascii: 'Chennai',
      lat: 13.09,
      lng: 80.28,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Tamil Nādu ',
      capital: 'admin',
      population: 7163000,
      id: 1356374944,
    },
    {
      city: 'Taipei',
      city_ascii: 'Taipei',
      lat: 25.0358,
      lng: 121.5683,
      country: 'Taiwan',
      iso2: 'TW',
      iso3: 'TWN',
      admin_name: 'Taipei',
      capital: 'primary',
      population: 6900273,
      id: 1158881289,
    },
    {
      city: 'Bengalūru',
      city_ascii: 'Bengaluru',
      lat: 12.97,
      lng: 77.56,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Karnātaka',
      capital: 'admin',
      population: 6787000,
      id: 1356410365,
    },
    {
      city: 'Bangkok',
      city_ascii: 'Bangkok',
      lat: 13.75,
      lng: 100.5166,
      country: 'Thailand',
      iso2: 'TH',
      iso3: 'THA',
      admin_name: 'Krung Thep Maha Nakhon',
      capital: 'primary',
      population: 6704000,
      id: 1764068610,
    },
    {
      city: 'Lahore',
      city_ascii: 'Lahore',
      lat: 31.56,
      lng: 74.35,
      country: 'Pakistan',
      iso2: 'PK',
      iso3: 'PAK',
      admin_name: 'Punjab',
      capital: 'admin',
      population: 6577000,
      id: 1586801463,
    },
    {
      city: 'Chongqing',
      city_ascii: 'Chongqing',
      lat: 29.565,
      lng: 106.595,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Chongqing',
      capital: 'admin',
      population: 6461000,
      id: 1156936556,
    },
    {
      city: 'Miami',
      city_ascii: 'Miami',
      lat: 25.7839,
      lng: -80.2102,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Florida',
      capital: '',
      population: 6381966,
      id: 1840015149,
    },
    {
      city: 'Hyderabad',
      city_ascii: 'Hyderabad',
      lat: 17.4,
      lng: 78.48,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Telangana',
      capital: 'admin',
      population: 6376000,
      id: 1356871768,
    },
    {
      city: 'Dallas',
      city_ascii: 'Dallas',
      lat: 32.7936,
      lng: -96.7662,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Texas',
      capital: '',
      population: 5733259,
      id: 1840019440,
    },
    {
      city: 'Santiago',
      city_ascii: 'Santiago',
      lat: -33.45,
      lng: -70.667,
      country: 'Chile',
      iso2: 'CL',
      iso3: 'CHL',
      admin_name: 'Región Metropolitana',
      capital: 'primary',
      population: 5720000,
      id: 1152554349,
    },
    {
      city: 'Philadelphia',
      city_ascii: 'Philadelphia',
      lat: 40.0077,
      lng: -75.1339,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Pennsylvania',
      capital: '',
      population: 5637884,
      id: 1840000673,
    },
    {
      city: 'Belo Horizonte',
      city_ascii: 'Belo Horizonte',
      lat: -19.915,
      lng: -43.915,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Minas Gerais',
      capital: 'admin',
      population: 5575000,
      id: 1076967355,
    },
    {
      city: 'Madrid',
      city_ascii: 'Madrid',
      lat: 40.4,
      lng: -3.6834,
      country: 'Spain',
      iso2: 'ES',
      iso3: 'ESP',
      admin_name: 'Madrid',
      capital: 'primary',
      population: 5567000,
      id: 1724616994,
    },
    {
      city: 'Houston',
      city_ascii: 'Houston',
      lat: 29.7869,
      lng: -95.3905,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Texas',
      capital: '',
      population: 5446468,
      id: 1840020925,
    },
    {
      city: 'Ahmadābād',
      city_ascii: 'Ahmadabad',
      lat: 23.0301,
      lng: 72.58,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Gujarāt',
      capital: 'minor',
      population: 5375000,
      id: 1356304381,
    },
    {
      city: 'Ho Chi Minh City',
      city_ascii: 'Ho Chi Minh City',
      lat: 10.78,
      lng: 106.695,
      country: 'Vietnam',
      iso2: 'VN',
      iso3: 'VNM',
      admin_name: 'Hồ Chí Minh',
      capital: 'admin',
      population: 5314000,
      id: 1704774326,
    },
    {
      city: 'Washington',
      city_ascii: 'Washington',
      lat: 38.9047,
      lng: -77.0163,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'District of Columbia',
      capital: 'primary',
      population: 5289420,
      id: 1840006060,
    },
    {
      city: 'Atlanta',
      city_ascii: 'Atlanta',
      lat: 33.7627,
      lng: -84.4225,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Georgia',
      capital: 'admin',
      population: 5228750,
      id: 1840013660,
    },
    {
      city: 'Toronto',
      city_ascii: 'Toronto',
      lat: 43.7,
      lng: -79.42,
      country: 'Canada',
      iso2: 'CA',
      iso3: 'CAN',
      admin_name: 'Ontario',
      capital: 'admin',
      population: 5213000,
      id: 1124279679,
    },
    {
      city: 'Singapore',
      city_ascii: 'Singapore',
      lat: 1.293,
      lng: 103.8558,
      country: 'Singapore',
      iso2: 'SG',
      iso3: 'SGP',
      admin_name: '',
      capital: 'primary',
      population: 5183700,
      id: 1702341327,
    },
    {
      city: 'Luanda',
      city_ascii: 'Luanda',
      lat: -8.8383,
      lng: 13.2344,
      country: 'Angola',
      iso2: 'AO',
      iso3: 'AGO',
      admin_name: 'Luanda',
      capital: 'primary',
      population: 5172900,
      id: 1024949724,
    },
    {
      city: 'Baghdad',
      city_ascii: 'Baghdad',
      lat: 33.3386,
      lng: 44.3939,
      country: 'Iraq',
      iso2: 'IQ',
      iso3: 'IRQ',
      admin_name: 'Baghdād',
      capital: 'primary',
      population: 5054000,
      id: 1368596238,
    },
    {
      city: 'Barcelona',
      city_ascii: 'Barcelona',
      lat: 41.3833,
      lng: 2.1834,
      country: 'Spain',
      iso2: 'ES',
      iso3: 'ESP',
      admin_name: 'Catalonia',
      capital: 'admin',
      population: 4920000,
      id: 1724594040,
    },
    {
      city: 'Hāora',
      city_ascii: 'Haora',
      lat: 22.5804,
      lng: 88.3299,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'West Bengal',
      capital: '',
      population: 4841638,
      id: 1356986516,
    },
    {
      city: 'Shenyang',
      city_ascii: 'Shenyang',
      lat: 41.805,
      lng: 123.45,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Liaoning',
      capital: 'admin',
      population: 4787000,
      id: 1156309382,
    },
    {
      city: 'Khartoum',
      city_ascii: 'Khartoum',
      lat: 15.5881,
      lng: 32.5342,
      country: 'Sudan',
      iso2: 'SD',
      iso3: 'SDN',
      admin_name: 'Khartoum',
      capital: 'primary',
      population: 4754000,
      id: 1729268475,
    },
    {
      city: 'Pune',
      city_ascii: 'Pune',
      lat: 18.53,
      lng: 73.85,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Mahārāshtra',
      capital: '',
      population: 4672000,
      id: 1356081074,
    },
    {
      city: 'Boston',
      city_ascii: 'Boston',
      lat: 42.3188,
      lng: -71.0846,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Massachusetts',
      capital: 'admin',
      population: 4637537,
      id: 1840000455,
    },
    {
      city: 'Sydney',
      city_ascii: 'Sydney',
      lat: -33.92,
      lng: 151.1852,
      country: 'Australia',
      iso2: 'AU',
      iso3: 'AUS',
      admin_name: 'New South Wales',
      capital: 'admin',
      population: 4630000,
      id: 1036074917,
    },
    {
      city: 'Saint Petersburg',
      city_ascii: 'Saint Petersburg',
      lat: 59.939,
      lng: 30.316,
      country: 'Russia',
      iso2: 'RU',
      iso3: 'RUS',
      admin_name: 'Sankt-Peterburg',
      capital: 'admin',
      population: 4553000,
      id: 1643616350,
    },
    {
      city: 'Chittagong',
      city_ascii: 'Chittagong',
      lat: 22.33,
      lng: 91.8,
      country: 'Bangladesh',
      iso2: 'BD',
      iso3: 'BGD',
      admin_name: 'Chittagong',
      capital: 'admin',
      population: 4529000,
      id: 1050830722,
    },
    {
      city: 'Dongguan',
      city_ascii: 'Dongguan',
      lat: 23.0489,
      lng: 113.7447,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Guangdong',
      capital: 'minor',
      population: 4528000,
      id: 1156478242,
    },
    {
      city: 'Riyadh',
      city_ascii: 'Riyadh',
      lat: 24.6408,
      lng: 46.7727,
      country: 'Saudi Arabia',
      iso2: 'SA',
      iso3: 'SAU',
      admin_name: 'Ar Riyāḑ',
      capital: 'primary',
      population: 4465000,
      id: 1682999334,
    },
    {
      city: 'Hanoi',
      city_ascii: 'Hanoi',
      lat: 21.0333,
      lng: 105.85,
      country: 'Vietnam',
      iso2: 'VN',
      iso3: 'VNM',
      admin_name: 'Hà Nội',
      capital: 'primary',
      population: 4378000,
      id: 1704413791,
    },
    {
      city: 'Guadalajara',
      city_ascii: 'Guadalajara',
      lat: 20.67,
      lng: -103.33,
      country: 'Mexico',
      iso2: 'MX',
      iso3: 'MEX',
      admin_name: 'Jalisco',
      capital: 'admin',
      population: 4198000,
      id: 1484950208,
    },
    {
      city: 'Melbourne',
      city_ascii: 'Melbourne',
      lat: -37.82,
      lng: 144.975,
      country: 'Australia',
      iso2: 'AU',
      iso3: 'AUS',
      admin_name: 'Victoria',
      capital: 'admin',
      population: 4170000,
      id: 1036533631,
    },
    {
      city: 'Alexandria',
      city_ascii: 'Alexandria',
      lat: 31.2,
      lng: 29.95,
      country: 'Egypt',
      iso2: 'EG',
      iso3: 'EGY',
      admin_name: 'Al Iskandarīyah',
      capital: 'admin',
      population: 4165000,
      id: 1818695837,
    },
    {
      city: 'Chengdu',
      city_ascii: 'Chengdu',
      lat: 30.67,
      lng: 104.07,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Sichuan',
      capital: 'admin',
      population: 4123000,
      id: 1156421555,
    },
    {
      city: 'Rangoon',
      city_ascii: 'Rangoon',
      lat: 16.7834,
      lng: 96.1667,
      country: 'Burma',
      iso2: 'MM',
      iso3: 'MMR',
      admin_name: 'Yangon',
      capital: 'primary',
      population: 4088000,
      id: 1104616656,
    },
    {
      city: 'Phoenix',
      city_ascii: 'Phoenix',
      lat: 33.5722,
      lng: -112.0891,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Arizona',
      capital: 'admin',
      population: 4081849,
      id: 1840020568,
    },
    {
      city: 'Xi’an',
      city_ascii: "Xi'an",
      lat: 34.275,
      lng: 108.895,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Shaanxi',
      capital: 'admin',
      population: 4009000,
      id: 1156244079,
    },
    {
      city: 'Porto Alegre',
      city_ascii: 'Porto Alegre',
      lat: -30.05,
      lng: -51.2,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Rio Grande do Sul',
      capital: 'admin',
      population: 3917000,
      id: 1076658221,
    },
    {
      city: 'Sūrat',
      city_ascii: 'Surat',
      lat: 21.2,
      lng: 72.84,
      country: 'India',
      iso2: 'IN',
      iso3: 'IND',
      admin_name: 'Gujarāt',
      capital: '',
      population: 3842000,
      id: 1356758738,
    },
    {
      city: 'Hechi',
      city_ascii: 'Hechi',
      lat: 23.0965,
      lng: 109.6091,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Guangxi',
      capital: '',
      population: 3830000,
      id: 1156868701,
    },
    {
      city: 'Abidjan',
      city_ascii: 'Abidjan',
      lat: 5.32,
      lng: -4.04,
      country: 'Côte D’Ivoire',
      iso2: 'CI',
      iso3: 'CIV',
      admin_name: 'Abidjan',
      capital: 'primary',
      population: 3802000,
      id: 1384207980,
    },
    {
      city: 'Brasília',
      city_ascii: 'Brasilia',
      lat: -15.7833,
      lng: -47.9161,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Distrito Federal',
      capital: 'primary',
      population: 3716996,
      id: 1076144436,
    },
    {
      city: 'Ankara',
      city_ascii: 'Ankara',
      lat: 39.9272,
      lng: 32.8644,
      country: 'Turkey',
      iso2: 'TR',
      iso3: 'TUR',
      admin_name: 'Ankara',
      capital: 'primary',
      population: 3716000,
      id: 1792572891,
    },
    {
      city: 'Monterrey',
      city_ascii: 'Monterrey',
      lat: 25.67,
      lng: -100.33,
      country: 'Mexico',
      iso2: 'MX',
      iso3: 'MEX',
      admin_name: 'Nuevo León',
      capital: 'admin',
      population: 3712000,
      id: 1484559591,
    },
    {
      city: 'Yokohama',
      city_ascii: 'Yokohama',
      lat: 35.32,
      lng: 139.58,
      country: 'Japan',
      iso2: 'JP',
      iso3: 'JPN',
      admin_name: 'Kanagawa',
      capital: 'admin',
      population: 3697894,
      id: 1392118339,
    },
    {
      city: 'Nanjing',
      city_ascii: 'Nanjing',
      lat: 32.05,
      lng: 118.78,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Jiangsu',
      capital: 'admin',
      population: 3679000,
      id: 1156644065,
    },
    {
      city: 'Montréal',
      city_ascii: 'Montreal',
      lat: 45.5,
      lng: -73.5833,
      country: 'Canada',
      iso2: 'CA',
      iso3: 'CAN',
      admin_name: 'Québec',
      capital: '',
      population: 3678000,
      id: 1124586170,
    },
    {
      city: 'Guiyang',
      city_ascii: 'Guiyang',
      lat: 26.58,
      lng: 106.72,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Guizhou',
      capital: 'admin',
      population: 3662000,
      id: 1156932620,
    },
    {
      city: 'Recife',
      city_ascii: 'Recife',
      lat: -8.0756,
      lng: -34.9156,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Pernambuco',
      capital: 'admin',
      population: 3651000,
      id: 1076137337,
    },
    {
      city: 'Seattle',
      city_ascii: 'Seattle',
      lat: 47.6211,
      lng: -122.3244,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Washington',
      capital: '',
      population: 3643765,
      id: 1840021117,
    },
    {
      city: 'Harbin',
      city_ascii: 'Harbin',
      lat: 45.75,
      lng: 126.65,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Heilongjiang',
      capital: 'admin',
      population: 3621000,
      id: 1156241528,
    },
    {
      city: 'San Francisco',
      city_ascii: 'San Francisco',
      lat: 37.7562,
      lng: -122.443,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'California',
      capital: '',
      population: 3603761,
      id: 1840021543,
    },
    {
      city: 'Fortaleza',
      city_ascii: 'Fortaleza',
      lat: -3.75,
      lng: -38.58,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Ceará',
      capital: 'admin',
      population: 3602319,
      id: 1076567885,
    },
    {
      city: 'Zhangzhou',
      city_ascii: 'Zhangzhou',
      lat: 24.5204,
      lng: 117.67,
      country: 'China',
      iso2: 'CN',
      iso3: 'CHN',
      admin_name: 'Fujian',
      capital: 'minor',
      population: 3531147,
      id: 1156241637,
    },
    {
      city: 'Detroit',
      city_ascii: 'Detroit',
      lat: 42.3834,
      lng: -83.1024,
      country: 'United States',
      iso2: 'US',
      iso3: 'USA',
      admin_name: 'Michigan',
      capital: '',
      population: 3522206,
      id: 1840003971,
    },
    {
      city: 'Salvador',
      city_ascii: 'Salvador',
      lat: -12.97,
      lng: -38.48,
      country: 'Brazil',
      iso2: 'BR',
      iso3: 'BRA',
      admin_name: 'Bahia',
      capital: 'admin',
      population: 3484000,
      id: 1076923789,
    },
  ];
}

export function getCategorizedStates() {
  return [
    { header: 'West' },
    { abbr: 'AZ', city: 'Arizona' },
    { abbr: 'CA', city: 'California' },
    { abbr: 'CO', city: 'Colorado' },
    { abbr: 'abbr', city: 'abbraho' },
    { abbr: 'MT', city: 'Montana' },
    { abbr: 'NV', city: 'Nevada' },
    { abbr: 'NM', city: 'New Mexico' },
    { abbr: 'OK', city: 'Oklahoma' },
    { abbr: 'OR', city: 'Oregon' },
    { abbr: 'TX', city: 'Texas' },
    { abbr: 'UT', city: 'Utah' },
    { abbr: 'WA', city: 'Washington' },
    { abbr: 'WY', city: 'Wyoming' },
    { header: 'Southeast' },
    { abbr: 'AL', city: 'Alabama' },
    { abbr: 'AR', city: 'Arkansas' },
    { abbr: 'FL', city: 'Florabbra' },
    { abbr: 'GA', city: 'Georgia' },
    { abbr: 'KY', city: 'Kentucky' },
    { abbr: 'LA', city: 'Louisiana' },
    { abbr: 'MS', city: 'Mississippi' },
    { abbr: 'NC', city: 'North Carolina' },
    { abbr: 'SC', city: 'South Carolina' },
    { abbr: 'TN', city: 'Tennessee' },
    { abbr: 'VA', city: 'Virginia' },
    { abbr: 'WV', city: 'West Virginia' },
    { header: 'Mabbrwest' },
    { abbr: 'IL', city: 'Illinois' },
    { abbr: 'IN', city: 'Indiana' },
    { abbr: 'IA', city: 'Iowa' },
    { abbr: 'KS', city: 'Kansas' },
    { abbr: 'MI', city: 'Michigan' },
    { abbr: 'MN', city: 'Minnesota' },
    { abbr: 'MO', city: 'Missouri' },
    { abbr: 'NE', city: 'Nebraska' },
    { abbr: 'OH', city: 'Ohio' },
    { abbr: 'ND', city: 'North Dakota' },
    { abbr: 'SD', city: 'South Dakota' },
    { abbr: 'WI', city: 'Wisconsin' },
    { header: 'Northeast' },
    { abbr: 'CT', city: 'Connecticut' },
    { abbr: 'DE', city: 'Delaware' },
    { abbr: 'ME', city: 'Maine' },
    { abbr: 'MD', city: 'Maryland' },
    { abbr: 'MA', city: 'Massachusetts' },
    { abbr: 'NH', city: 'New Hampshire' },
    { abbr: 'NJ', city: 'New Jersey' },
    { abbr: 'NY', city: 'New York' },
    { abbr: 'PA', city: 'Pennsylvania' },
    { abbr: 'RI', city: 'Rhode Island' },
    { abbr: 'VT', city: 'Vermont' },
    { header: 'Pacific' },
    { abbr: 'AK', city: 'Alaska' },
    { abbr: 'HI', city: 'Hawaii' },
  ];
}

export function getCity(pCity, pCountry) {
  const dataArray = getStates(pCity);
  return dataArray.find(x => x.city === pCity.trim() && x.country === pCountry.trim());
}
